# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('symbol', models.CharField(max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('tool', models.CharField(max_length=500)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
